[appearance.theme]
palette_source = "wallpaper"

[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.67999998480081558
    capsule = true
    capsule_opacity = 0.91999997943639755
    center = [ "group:g3", "group:g5", "group:g7" ]
    concave_edge_corners = false
    end = [ "group:g4", "group:g6", "group:g2", "group:g8", "session" ]
    margin_edge = 8
    margin_ends = 9
    radius = 22
    start = [ "launcher", "group:g1", "taskbar", "status" ]
    thickness = 45

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "wallpaper", "wallhaven" ]
    opacity = 0.91999995708465576
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "battery", "brightness", "volume" ]
    opacity = 0.91999995708465576
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "cat", "ram" ]
    opacity = 0.91999995708465576
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "tray_group_icon", "tray" ]
    opacity = 0.91999995708465576
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g5"
    members = [ "audio_visualizer", "media" ]
    opacity = 0.91999995708465576
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g6"
    members = [ "network", "bluetooth" ]
    opacity = 0.91999995708465576
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g7"
    members = [ "group_icon", "launcher_2", "vpn_widget" ]
    opacity = 0.91999995708465576
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g8"
    members = [ "notifications", "keyboard_layout", "clock", "control-center" ]
    opacity = 0.91999995708465576
    padding = 6.0

[control_center]
hidden_tabs = [ "power", "bluetooth" ]

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "bluetooth"

[dock]
background_opacity = 0.68999998457729816
concave_edge_corners = false
enabled = true
inactive_opacity = 0.99999997764825821
launcher_position = "start"
margin_edge = 8
pinned = [ "code", "firefox", "org.gnome.Nautilus", "kitty", "dev.zed.Zed" ]
radius = 32
reserve_space = false
show_dots = true
smart_auto_hide = true

[keybinds]
down = [ "Down", "Ctrl+n" ]
up = [ "Up", "Ctrl+p" ]

[location]
address = "Moscow, Russia"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@Virtual-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.00006103515625
    cy = 897.999755859375
    output = "Virtual-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.81999998167157173

[osd]
background_opacity = 0.56999998725950718

[plugin_settings."aabidk20/yt-music"]
mini_open_near_click = true

[plugin_settings."dotnetrob/cat"]
panel_placement = "floating"

[plugin_settings."mindnbytes/nix-status"]
details_placement = "floating"
flake_dir = "/home/litc/Nixos"
nixos_configuration = "litc-nixos-pc"

[plugin_settings."noctalia/wallhaven"]
browser_open_near_click = true
browser_placement = "floating"
download_dir = "/home/litc/Pictures/Wallpapers/Wallheaven"

[plugin_settings."tordex/nvtop"]
sort_column_color = "on_surface"

[plugin_settings."umedbazarov/ruh-vpn"]
auto_start = true
vpn_panel_placement = "floating"
vpn_panel_position = "top_center"

[plugins]
auto_update = "all"
enabled = [
    "noctalia/wallhaven",
    "dotnetrob/cat",
    "knyrps/nix-search",
    "umedbazarov/ruh-vpn",
    "kenn/keybind-cheatsheet",
    "mindnbytes/nix-status",
    "icefish/phone-operate",
    "alexander/game-launcher"
]

[shell]
external_ip_enabled = true
niri_overview_type_to_launch_enabled = true
polkit_agent = true

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    open_near_click_wallpaper = true
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [shell.screenshot]
    confirm_region = true
    directory = "/home/litc/Pictures/Screenshots"
    remember_last_region = false

    [shell.window_switcher]
    mru = true

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Storm"
custom_palette = "_live_preview"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "foot", "gtk3", "gtk4", "kitty", "niri", "qt" ]
    community_ids = [
        "antigravity",
        "pywalfox",
        "discord",
        "telegram",
        "neovim",
        "obsidian",
        "vscode",
        "zed",
        "heroiclauncher",
        "yazi"
    ]

        [theme.templates.user.kcolorscheme]
        input_path = "/home/litc/Nixos/home/kcolorscheme.colors"
        output_path = "/home/litc/.local/share/color-schemes/noctalia.colors"

        [theme.templates.user.obsidian_extra]
        input_path = "/home/litc/.local/state/noctalia/community-templates/obsidian/obsidian.css"
        output_path = "/home/litc/Obsidian/Vault/.obsidian/snippets/noctalia.css"

        [theme.templates.user.palette_creator_live]
        input_path = "/home/litc/.local/state/noctalia/plugins/materialized/community/palette-creator/templates/live-snapshot.tpl"
        output_path = "/home/litc/.local/state/noctalia/plugin-data/kyle-palette-creator/live-snapshot.json"

[wallpaper]
directory = "/home/litc/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/litc/Pictures/Wallpapers/Wallheaven/wallhaven-rr67vm.png"

    [wallpaper.last]
    path = "/home/litc/Pictures/Wallpapers/Wallheaven/wallhaven-rr67vm.png"

    [wallpaper.monitors.Virtual-1]
    path = "/home/litc/Pictures/wallpaper.png"

[widget.active-workspace]
type = "salemsayed/niri-active-workspace:active-workspace"

[widget.audio_visualizer]
bands = 14
color_2 = "secondary"
show_when_idle = false
width = 90

[widget.cat]
cat_size = 35
show_cpu_percent = true
type = "dotnetrob/cat:cat"

[widget.clipboard]
enabled = false

[widget.control-center]
glyph = "brand-snowflake"

[widget.current]
type = "thaer99ob/default-apps:current"

[widget.group_icon]
glyph = "layout-sidebar-left-expand-filled"
tooltip = "Expand Group"
type = "custom_button"

    [widget.group_icon.actions]
    left = "none"

[widget.launcher_2]
type = "alexander/game-launcher:launcher"

[widget.media]
hide_when_no_media = true
max_length = 176
title_scroll = "always"

[widget.network]
show_label = false

[widget.status]
type = "mindnbytes/nix-status:status"

[widget.taskbar]
group_by_workspace = true
group_single_icon_per_app = false
hide_empty_workspaces = false
icon_scale = 1.2000000000000002
show_active_indicator = false
show_workspace_label = true
workspace_group_capsule = true
workspace_group_content = "icons"
workspace_label_placement = "corner"

[widget.toggle]
type = "decksters-lab/palette-creator:toggle"

[widget.tray_group_icon]
glyph = "chevron-left"
type = "custom_button"

[widget.vpn_widget]
show_ping = false
type = "umedbazarov/ruh-vpn:vpn_widget"

[widget.wallhaven]
glyph = "cloud-download"
type = "noctalia/wallhaven:wallhaven"

[widget.widget]
type = "aabidk20/yt-music:widget"

[widget.widget_2]
type = "tadomika_ari/config-swap:widget"

[widget.widget_3]
type = "tordex/processes:widget"

[widget.widget_4]
type = "weinguyen/procmon:widget"
