config_version = 14

[accessibility]
ui_scale = 0.90000000596046448

[bar.default]
background_opacity = 0.96999997831881046
border = "primary"
border_width = 1.0
capsule_fill = "surface"
capsule_thickness = 0.80999998562037945
margin_edge = 4
start = [ "launcher", "group:g1", "taskbar" ]
thickness = 42

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "wallpaper", "wallhaven" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "battery", "brightness", "volume" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "cat", "ram" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "start"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "tray_group_icon", "tray" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g5"
    members = [ "audio_visualizer", "media" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g6"
    members = [ "network", "bluetooth" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g7"
    members = [ "group_icon", "status", "launcher_2", "vpn_widget" ]
    opacity = 0.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g8"
    members = [ "notifications", "keyboard_layout", "clock", "control-center" ]
    opacity = 0.0
    padding = 6.0

[control_center]
hidden_tabs = []

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "bluetooth"

[dock]
background_opacity = 0.96999997831881046
border = "primary"
border_width = 1.5
icon_size = 39
margin_edge = 4

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@eDP-1", "lockscreen-login-box@Virtual-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.00006103515625
    cy = 897.999755859375
    output = "Virtual-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 683.00006103515625
    cy = 586.0001220703125
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 720.0
    cx = 675.00006103515625
    cy = 517.0
    output = "winit"
    placement_height = 699.0
    placement_width = 1350.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.96999997831881046

[osd]
background_opacity = 0.96999997831881046

[plugins]
enabled = [
    "noctalia/wallhaven",
    "dotnetrob/cat",
    "knyrps/nix-search",
    "umedbazarov/ruh-vpn",
    "kenn/keybind-cheatsheet",
    "mindnbytes/nix-status",
    "icefish/phone-operate",
    "alexander/game-launcher",
    "oldirtty/color_picker"
]

[shell]
settings_show_advanced = false

    [shell.panel]
    transparency_mode = "solid"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl soft-reboot"
    countdown_seconds = 0.0
    enabled = true
    glyph = "building-wind-turbine"
    label = "Soft Reboot"
    shortcut = "5"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "6"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.82999998144805431

[theme]
builtin = "Ayu"
community_palette = "Catppuccin Mocha Blue"
custom_palette = "marisa-blue"
mode = "dark"
source = "custom"
wallpaper_scheme = "m3-content"

    [theme.templates]
    community_ids = [
        "antigravity",
        "pywalfox",
        "discord",
        "telegram",
        "neovim",
        "obsidian",
        "vscode",
        "zed",
        "heroiclauncher",
        "steam",
        "yazi"
    ]

[wallpaper.default]
path = "/home/litc/Pictures/Wallpapers/Wallheaven/wallhaven-rr67vm.png"

[wallpaper.last]
path = "/home/litc/Pictures/Wallpapers/Wallheaven/wallhaven-rr67vm.png"

[wallpaper.monitors.eDP-1]
path = "/home/litc/Pictures/Wallpapers/Wallheaven/wallhaven-rr67vm.png"

[[wallpaper.favorite]]
custom_palette = "marisa-blue"
palette_source = "custom"
path = "/home/litc/Pictures/Wallpapers/Wallheaven/wallhaven-jx85w5.png"
theme_mode = "dark"

[[wallpaper.favorite]]
custom_palette = "ayu-edit"
palette_source = "custom"
path = "/home/litc/Pictures/Wallpapers/Wallheaven/wallhaven-rr67vm.png"
theme_mode = "dark"

[widget.media]
max_length = 148
min_length = 50

[widget.taskbar]
workspace_label_placement = "inside"